FROM golang

WORKDIR /go/src/app
COPY . .
#直接镜像内打包编译
RUN export GO111MODULE=auto && export GOPROXY=https://goproxy.cn && go mod tidy
RUN go build -o ./bin/gateway_micro

CMD ./bin/gateway_micro -config=./conf/dev/ -endpoint=dashboard